- name: Deploy Python Application
  hosts: all
  become: yes
  vars:
    docker_image: 'ghostvern/ping-dnsapp:v1.0'
    container_name: 'my_ping_dns_app'
    container_port: 5000

  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Docker module for Python
      pip:
        name: docker
        executable: pip3

    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: latest

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull application image from DockerHub
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run the application container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ container_port }}:5000"
